### ISSUE TITLE
get it to start in docker, even if it requires an ugly x server hack

### ISSUE THREAD

**Issue by pushfoo** [Creatures-Developer-Network/docker-ds#1]
@Kirtai posted a [gist overview of how they get lc2e running](https://gist.github.com/Kirtai/6ded27834a822ba835daabcd66f8f4dc) under normal linux.

That overview + xvfb or a [windows equivalent ](https://medium.com/@dhanar.santika/installing-wsl-with-gui-using-vcxsrv-6f307e96fac0) may be a good foundation. On Windows, [Docker is soon coming to Windows Home through WSL 2](https://docs.docker.com/docker-for-windows/release-notes/), so there might be a way of getting DS working in 32 bit color without color change issues. I'm not sure how user friendly we can make it, but it's worth trying. It might give us the start of a cross-platform DS image, or at least a way to build one.

**Comment by robinduckett** [comment]
Does creatures for Linux work with the WSL?

**Comment by pushfoo** [comment]
Maybe. I haven't heard good things about running games on previous WSL versions, but it's worth trying. 
The point of getting it working in docker is that OS X, Windows, and Linux could then all have a consistent c2e version. I know it could be installed natively on Linux, but I figure it's worth the option of having a consistent install process that doesn't touch system files. There's a rootless docker mode I heard about that I'm hoping can now be enabled by default on linux. I haven't read the doc extensively though, so it might not work by default.

**Comment by Kirtai** [comment]
For the record, there doesn't seem to be any colour change issues on a 32bit display. SDL seems to handle the 16->32bit conversion itself, though there is a warning of a performance hit.
```
Creatures 3 found at /zpool/games/docking-station/C3

You can type dockingstation to run the game from
now on.  The original dstation-install file can be
deleted, as dockingstation will also check for updates.

Welcome to Docking Station!

Video information:
  32 bits per pixel, 4 bytes per pixel
  rmask: 0xff0000 gmask: 0xff00 bmask: 0xff
  Display is 32 bit
  WARNING - there will be a performance hit.
            For best results, set your display depth
            to 16 (or 15) bits in X configuration.
  Available fullscreen modes: 3760x1920 2560x1440 1920x1200 1920x1080 1920x1080 1680x1050 1600x1200 1440x900 1366x768 1280x1024 1280x800 1280x720 1280x720 1024x768 800x600 720x480 640x480 640x480 
Initializing Sound

CAOS injection bound to port 20001
```
Note that I have a weird dual screen setup with a portrait 1920x1200 monitor, hence some of the weird display sizes. 

Also attached a screenshot of it running on Kubuntu 20.04.


![Screenshot_20200513_002023](https://user-images.githubusercontent.com/3085457/81755040-92b8e580-94af-11ea-8b52-1eadcd4c598d.png)

**Comment by pushfoo** [comment]
@Kirtai
>  there doesn't seem to be any colour change issues on a 32bit display

That's part of why I want to explore lc2e. Windows c2e is finicky. If lc2e doesn't turn out to be something that can be made as easy to install as OpenMW, there are various directX intercept kludges ([dxwnd](https://sourceforge.net/projects/dxwnd/) , [DirectX-Wrappers](https://github.com/elishacloud/DirectX-Wrappers) that could be tried to force c2e to draw in 32 bit mode. However, I think I heard that other games have varying and hardware-dependent degrees of success with them. 
I don't remember if you made a separate repo yet or not. If you want, we can make this repo a grab bag of lc2e documentation and scripts, including a dockerfile. @robinduckett thoughts? @Kirtai, By all means please merge your gist as a guide or something if you haven't yet made a repo. I don't want to take credit on it from you.

**Comment by Kirtai** [comment]
I've been thinking about how to do a docker image or flatpak of docking station and the need to be able to mod/patch the game vastly complicates it. :(

Maybe I'm missing something though.

**Comment by robinduckett** [comment]
This is where I'm currently at, just having a bind mount volume of .dockingstation doesn't work - We may be able to extract the required files by commiting to a new image just the container stops and then copying the files from the new image

**Comment by pushfoo** [comment]
@Kirtai it's not that big of an issue imo. I've thought about it before, and mounting resource directories in as volumes should make it drastically easier. Eventually, that could play nucely with a package manager.
@robinduckett we may need to write a config file that gets added into the container. Idk what defaults lc2e has for directories. I might have old notes somewhere on how to do that, but look at the config files lc2e generates by default.
I'm not sure i want to put managing c2e assets into containers for a variety of reasons. In my opinion, the ideal eventual goal should be a bare engine container that we ship, and can swap out for openc2e when needed.

**Comment by robinduckett** [comment]
Okay well let me know what needs to be done next or if you're happy to tinker with it as is

**Comment by pushfoo** [comment]
The bare engine thing doesn't need to happen in this ticket. PR #3 closes this issue, correct?

**Comment by robinduckett** [comment]
Yep, although I will need to make some issues to track the problems I'm encountering
